name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tnt: [1.6, 1.7, 1.9, 1, 2, 2.1]
        java: [1.8, 11]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: start tarantool
      run: docker run -d -p 3301:3301 -e TARANTOOL_USER_NAME=admin -e TARANTOOL_USER_PASSWORD=javapass tarantool/tarantool:${{ matrix.tnt }}
    - name: Build
      env:
        TARANTOOL_VERSION: ${{ matrix.tnt }}
      run: ./mvnw clean verify
